# Generated by Django 2.2.12 on 2020-04-12 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import view_block.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passports', djongo.models.fields.ArrayModelField(model_container=view_block.models.Passport)),
                ('international_passports', djongo.models.fields.ArrayModelField(model_container=view_block.models.InternationalPassport)),
                ('driver_licenses', djongo.models.fields.ArrayModelField(model_container=view_block.models.DriverLicense)),
                ('insurance_certificate', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.InsuranceCertificate, null=True)),
                ('policy', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.Policy, null=True)),
                ('birth_certificate', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.BirthCertificate, null=True)),
                ('military_id', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.MilitaryID, null=True)),
                ('employment_history', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.EmploymentHistory, null=True)),
                ('education_documents', djongo.models.fields.ArrayModelField(model_container=view_block.models.EducationDocument)),
                ('itn', models.CharField(db_column='ITN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(blank=True, max_length=255, null=True)),
                ('search_value', models.CharField(max_length=255)),
                ('search_timestamp', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_info', djongo.models.fields.EmbeddedModelField(model_container=view_block.models.MainInfo, null=True)),
                ('kindergartens', djongo.models.fields.ArrayModelField(model_container=view_block.models.Kindergarten)),
                ('schools', djongo.models.fields.ArrayModelField(model_container=view_block.models.School)),
                ('colleges', djongo.models.fields.ArrayModelField(model_container=view_block.models.College)),
                ('universities', djongo.models.fields.ArrayModelField(model_container=view_block.models.University)),
                ('works', djongo.models.fields.ArrayModelField(model_container=view_block.models.Work)),
                ('interests', djongo.models.fields.ArrayModelField(model_container=view_block.models.Interest)),
                ('incomes', djongo.models.fields.ArrayModelField(model_container=view_block.models.Income)),
                ('expenses', djongo.models.fields.ArrayModelField(model_container=view_block.models.Expenses)),
                ('bank_accounts', djongo.models.fields.ArrayModelField(model_container=view_block.models.BankAccount)),
                ('electronic_wallets', djongo.models.fields.ArrayModelField(model_container=view_block.models.ElectronicWallet)),
                ('estate', djongo.models.fields.ArrayModelField(model_container=view_block.models.Estate)),
                ('social_networks', djongo.models.fields.ArrayModelField(model_container=view_block.models.SocialNetwork)),
                ('messengers', djongo.models.fields.ArrayModelField(model_container=view_block.models.Messenger)),
                ('emails', djongo.models.fields.ArrayModelField(model_container=view_block.models.Email)),
                ('game_platforms', djongo.models.fields.ArrayModelField(model_container=view_block.models.GamePlatform)),
                ('forums', djongo.models.fields.ArrayModelField(model_container=view_block.models.Forum)),
                ('MAC_addresses', djongo.models.fields.ArrayModelField(model_container=view_block.models.MAC)),
                ('IP_addresses', djongo.models.fields.ArrayModelField(model_container=view_block.models.IP)),
                ('HWIDs', djongo.models.fields.ArrayModelField(model_container=view_block.models.HWID)),
                ('DNSs', djongo.models.fields.ArrayModelField(model_container=view_block.models.DNS)),
                ('geo_tags', djongo.models.fields.ArrayModelField(model_container=view_block.models.GeoTags)),
                ('phones', djongo.models.fields.ArrayModelField(model_container=view_block.models.Phone)),
                ('documents', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='view_block.Document')),
            ],
        ),
    ]
