# Generated by Django 2.2.12 on 2021-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='search_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
